#!/bin/bash
set -e -a

: ${NRSCONFIG_NOBUILD:=0}

if [ -z ${CC} ] || [ -z ${CXX}  ] || [ -z ${FC}  ]; then
  echo -e "\033[31mERROR: env-var CC, CXX or FC is not set!\033[m"
  echo "Please try again using e.g. CC=mpicc CXX=mpic++ FC=mpif77 ./nrsconfig"
  exit 1
fi

cmd="cmake -S . -B build -Wfatal-errors $@" 
echo $cmd
eval $cmd 
if [ $? -eq 0 ] && [ ${NRSCONFIG_NOBUILD} -eq 0 ]; then
  cmd="cmake --build ./build --target install -j8" 
  echo ""    
  echo $cmd   
  read -p "Press ENTER to continue or ctrl-c to cancel"

  eval $cmd
  if [ $? -eq 0 ]; then
    echo ""
    echo -e "\033[35mHooray! You're all set. The installation is complete.\033[m"
    echo ""
  fi
fi
