#!/bin/bash

source $NEKRS_HOME/bin/nrsqsub_utils

#--------------------------------------
: ${QUEUE:="workq"}
: ${NEKRS_GPU_MPI:=1}
: ${NEKRS_BACKEND:="dpcpp"}
: ${OCCA_DPCPP_COMPILER_FLAGS:="-w -O3 -fsycl -gline-tables-only -fsycl-targets=intel_gpu_pvc -Xsycl-target-backend '-options -ze-intel-enable-auto-large-GRF-mode'"}
: ${GPUS_PER_NODE:=12}
: ${RANKS_FOR_BUILD:=12}
: ${ONEAPI_MODULE:="oneapi/eng-compiler/2023.05.15.006"}
: ${MPICH_MODULE:="mpich/51.2/icc-all-pmix-gpu"}
: ${CMAKE_MODULE:="spack cmake"}
: ${CPU_BIND_LIST:="0-7,104-111:8-15,112-119:16-23,120-127:24-31,128-135:32-39,136-143:40-47,144-151:52-59,156-163:60-67,164-171:68-75,172-179:76-83,180-187:84-91,188-195:92-99,196-203"}
#--------------------------------------

setup $case $#

RANKS_PER_NODE=$GPUS_PER_NODE
TOTAL_RANKS=$(( nodes * RANKS_PER_NODE ))

#--------------------------------------
# Generate the submission script
SFILE=s.bin
echo "#!/bin/bash" > $SFILE
echo "#PBS -A $PROJ_ID" >>$SFILE
echo "#PBS -N nekRS_$case" >>$SFILE
echo "#PBS -l walltime=${time}:00" >>$SFILE
echo "#PBS -l select=$nodes" >>$SFILE
echo "#PBS -l place=scatter" >>$SFILE
echo "#PBS -k doe" >>$SFILE
echo "#PBS -j oe" >>$SFILE

# job to "run" from your submission directory
echo "cd \$PBS_O_WORKDIR" >> $SFILE

echo "echo Jobid: \$PBS_JOBID" >>$SFILE
echo "echo Running on host \`hostname\`" >>$SFILE
echo "echo Running on nodes \`cat \$PBS_NODEFILE\`" >>$SFILE

echo "module load $ONEAPI_MODULE" >> $SFILE
# echo "module load $MPICH_MODULE" >> $SFILE
echo "module load $CMAKE_MODULE" >> $SFILE
echo "module list" >> $SFILE

echo "export NEKRS_HOME=$NEKRS_HOME" >>$SFILE
echo "export NEKRS_GPU_MPI=$NEKRS_GPU_MPI" >>$SFILE
echo "export MPICH_GPU_SUPPORT_ENABLED=$NEKRS_GPU_MPI" >> $SFILE

# https://github.com/Nek5000/Nek5000/issues/759
echo "export FI_CXI_RX_MATCH_MODE=hybrid" >> $SFILE 

echo "export TZ='/usr/share/zoneinfo/US/Central'" >> $SFILE
echo "export OMP_PROC_BIND=spread" >> $SFILE
echo "export OMP_NUM_THREADS=1" >> $SFILE
echo "unset OMP_PLACES" >> $SFILE

echo "export OCCA_DPCPP_COMPILER_FLAGS=\"$OCCA_DPCPP_COMPILER_FLAGS\"" >> $SFILE
echo "export SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=1" >> $SFILE

COMMAND="/soft/tools/mpi_wrapper_utils/gpu_tile_compact.sh ${bin}"

if [ $NEKRS_SKIP_BUILD_ONLY -eq 0 ]; then
  echo "# precompile"  >>$SFILE
  echo "date"  >>$SFILE
  echo "mpiexec -n ${RANKS_FOR_BUILD} ${COMMAND} --setup ${case} --backend ${NEKRS_BACKEND} --device-id 0 --build-only ${TOTAL_RANKS}" >> $SFILE
fi

echo "mpiexec -n ${TOTAL_RANKS} -ppn ${RANKS_PER_NODE} --cpu-bind=list:${CPU_BIND_LIST} ${COMMAND} --setup ${case} --backend ${NEKRS_BACKEND} --device-id 0" >> $SFILE

qsub -q $QUEUE $SFILE

# clean-up
