#!/bin/bash
source $NEKRS_HOME/bin/nrsqsub_utils

#--------------------------------------
: ${NEKRS_GPU_MPI:=1}
: ${NEKRS_BACKEND:="dpcpp"}
: ${OCCA_DPCPP_COMPILER_FLAGS:="-w -O3 -fsycl -gline-tables-only -fsycl-targets=intel_gpu_pvc -Xsycl-target-backend '-options -ze-intel-enable-auto-large-GRF-mode'"}
: ${GPUS_PER_NODE:=12}
: ${ONEAPI_MODULE:="oneapi/eng-compiler/2023.05.15.006"}
: ${MPICH_MODULE:="mpich/52.2"}
#--------------------------------------

setup $case $#

cores_per_numa=16
let nn=$nodes*$GPUS_PER_NODE
let ntasks=nn

#--------------------------------------
# Generate the submission script
SFILE=s.bin
echo "#!/bin/bash" >> $SFILE
echo "#PBS -A $PROJ_ID" >>$SFILE
echo "#PBS -N nekRS_$case" >>$SFILE
echo "#PBS -l walltime=$time:00" >>$SFILE
echo "#PBS -l select=$nodes" >>$SFILE
echo "#PBS -l place=scatter" >>$SFILE
echo "#PBS -k doe" >>$SFILE
echo "#PBS -j oe" >>$SFILE

# job to "run" from your submission directory
echo "cd \$PBS_O_WORKDIR" >> $SFILE

echo "echo Jobid: \$PBS_JOBID" >>$SFILE
echo "echo Running on host \`hostname\`" >>$SFILE
echo "echo Running on nodes \`cat \$PBS_NODEFILE\`" >>$SFILE

echo "module load $ONEAPI_MODULE" >> $SFILE
echo "module swap mpich $MPICH_MODULE" >> $SFILE
echo "module load spack-pe-gcc cmake" >> $SFILE
echo "module list" >> $SFILE

echo "export NEKRS_HOME=$NEKRS_HOME" >>$SFILE
echo "export NEKRS_GPU_MPI=$NEKRS_GPU_MPI" >>$SFILE
echo "export MPICH_GPU_SUPPORT_ENABLED=$NEKRS_GPU_MPI" >> $SFILE

# https://github.com/Nek5000/Nek5000/issues/759
echo "export FI_CXI_RX_MATCH_MODE=hybrid" >> $SFILE 

echo "export TZ='/usr/share/zoneinfo/US/Central'" >> $SFILE
echo "export OMP_PROC_BIND=spread" >> $SFILE
echo "export OMP_NUM_THREADS=1" >> $SFILE
echo "unset OMP_PLACES" >> $SFILE

echo "export OCCA_DPCPP_COMPILER_FLAGS=\"$OCCA_DPCPP_COMPILER_FLAGS\"" >> $SFILE
echo "export SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=1" >> $SFILE

if [ -d .cache ]; then
  rm -r .cache
fi

if [ $NEKRS_SKIP_BUILD_ONLY -eq 0 ]; then
echo "# precompile"  >>$SFILE
echo "date"  >>$SFILE
echo "mpiexec -n 1 $bin --setup ${case} --backend ${NEKRS_BACKEND} --device-id 0 --build-only $nn" >>$SFILE
fi

CMD="/soft/tools/mpi_wrapper_utils/gpu_tile_compact.sh"

echo "mpiexec -n $nn -ppn $GPUS_PER_NODE -d $cores_per_numa --cpu-bind depth $CMD $bin --setup ${case} --backend ${NEKRS_BACKEND} --device-id 0" >>$SFILE

qsub -q $QUEUE $SFILE

# clean-up
# rm -rf $SFILE 
